const levels = [
  {
    levelName: 'Lemur Cage',
    img: 'lemur-cage.jpg',
    relXStart: 0.55,
    relXEnd: 0.66,
    relYStart: 0.07,
    relYEnd: 0.19,
  },
  {
    levelName: 'Smart Cage',
    img: 'smart-cage.jpg',
    relXStart: 0.18,
    relXEnd: 0.22,
    relYStart: 0.14,
    relYEnd: 0.24,
  },
  {
    levelName: 'Classy Cage',
    img: 'classy-cage.jpg',
    relXStart: 0.43,
    relXEnd: 0.46,
    relYStart: 0.3,
    relYEnd: 0.37,
    found: false,
  },
  {
    levelName: 'Bieber Cage',
    img: 'bieber-cage.jpg',
    relXStart: 0.3,
    relXEnd: 0.39,
    relYStart: 0.0,
    relYEnd: 0.18,
  },

  {
    levelName: 'Karate Cage',
    img: 'karate-cage.jpg',
    relXStart: 0.13,
    relXEnd: 0.15,
    relYStart: 0.42,
    relYEnd: 0.45,
  },
  {
    levelName: 'Orchestra Cage',
    img: 'orchestra-cage.jpg',
    relXStart: 0.7,
    relXEnd: 0.72,
    relYStart: 0.26,
    relYEnd: 0.31,
  },
  {
    levelName: 'Constitution Cage',
    img: 'constitution-cage.jpg',
    relXStart: 0.21,
    relXEnd: 0.22,
    relYStart: 0.53,
    relYEnd: 0.56,
  },
  {
    levelName: 'Crowd Cage',
    img: 'crowd-cage.jpg',
    relXStart: 0.94,
    relXEnd: 0.97,
    relYStart: 0.31,
    relYEnd: 0.36,
  },
];

export default levels;
